version: '3.4'
services:
    apache2:
        container_name: demo_dind
        image: rose-demo
        privileged: true
        ports:
            - "5030:80"
        volumes:
            - ./rose_www:/var/www/localhost
        command:
            - --experimental

volumes:
    sessions:
    networks:
