version: '3.4'
services:
    apache2:
        container_name: demo_apache
        image: httpd:rose-apache
        #image: httpd:alpine
        ports:
            - "5030:80"
        volumes:
            #- ./www:/var/www
            - ./www/html:/usr/local/apache2/htdocs/
            
    demo:
        # pwd daemon container always needs to be named this way
        container_name: test_demo
        # use the latest golang image
        image: golang
        #volumes:
volumes:
    sessions:
    networks:
