version: '3.4'
services:
    apache2:
        container_name: demo_apache
        image: httpd:rose-apache
        ports:
            - "5030:80"
        volumes:
            - ./www/html:/usr/local/apache2/htdocs/
            - ./www/cgi-bin:/usr/local/apache2/cgi-bin
            
    demo:
        container_name: test_demo
        # ROSE compiler image
        image: golang
        #volumes:
volumes:
    sessions:
    networks:
