version: '3.4'
services:
    apache2:
        container_name: demo_apache
        image: httpd:rose-apache
        ports:
            - "5030:80"
        volumes:
            - ./rose_www/html:/usr/local/apache2/htdocs/
            - ./rose_www/cgi-bin:/usr/local/apache2/cgi-bin
            - /var/run/docker.sock:/var/run/docker.sock
            
    demo:
        container_name: demo_rose
        # ROSE compiler image
        image: rosedev:0.1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
volumes:
    sessions:
    networks:
