name: Docker Image CI

on:
  push:
    branches: [ master ]
    #paths: 
    #  - 'Dockerfile.frontend'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile.frontend --tag react

    - name: Push the Docker image
      run: |
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_ID }} --password-stdin
        docker tag react ouankou/rose:frontend
        docker push ouankou/rose:frontend
